groups:
  - name: likes_alerts
    rules:
      - alert: HighLikeTraffic
        expr: rate(likes_total{endpoint="/like"}[5m]) > 100000
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High like traffic detected"
          description: "Like requests per second exceeded 100,000 for 1 minute."